#!/bin/sh

CC=gcc
BIN_DIR=target/bin

mkdir -p ${BIN_DIR};

COMMAND="${CC} \
	-mavx2 \
	-fno-stack-clash-protection \
	-nostdlib \
	-std=c89 \
	-pedantic \
	-Werror \
	-Wall \
	-Wextra \
	-Wshadow \
	-Wpointer-arith \
	-Wcast-qual \
	-Wmissing-prototypes \
	-Wmissing-declarations \
	-o ${BIN_DIR}/test \
	main.c"

#COMMAND="${CC} -fvisibility=hidden -nostdlib -shared -fPIC -O3 -mavx2 -DCOMPRESS_IMPL -x c include/compress.h -o libcompress.so"

echo ${COMMAND};
${COMMAND};
