#!/bin/sh

ALL=0;
TEST=0;
CLEAN=0;
INSTALL=0;
INSTALL_LIB=0;
COVERAGE=0;
CC="${CC:-clang}"
CFLAGS="${CFLAGS:--O3 -fno-stack-clash-protection}"
MARCH="${MARCH:-native}";
VALGRIND="${VALGRIND:-0}"
TEST_DIR=./test
INCLUDE_DIR=include
INCLUDE="-I${INCLUDE_DIR}";
CSTRICT="-nostdlib \
	-fno-builtin \
	-fvisibility=hidden \
        -std=c99 \
        -Werror \
        -Wextra \
        -Wshadow \
        -Wpointer-arith \
        -Wcast-qual \
        -Wmissing-prototypes \
        -Wmissing-declarations"
BIN_DIR=./target/bin

for arg in "$@"; do
    case "$arg" in
        all)
            ALL=1;
	    LIB_DIR=./target/lib
            ;;
	test)
	    TEST=1;
	    LIB_DIR=./target/libtest
	    ;;
	cov)
	    COVERAGE=1;
	    LIB_DIR=./target/libcov
	    ;;
	clean)
	    CLEAN=1;
	    ;;
	install)
	    INSTALL=1;
	    ;;
        install_lib)
            INSTALL_LIB=1;
	    LIB_DIR=./target/lib
            ;;
        *)
	    echo "Invalid command";
	    exit 1;
	    ;;
    esac
done

if [ "${CLEAN}" = "0" ] &&
   [ "${TEST}" = "0" ] &&
   [ "${INSTALL}" = "0" ] &&
   [ "${COVERAGE}" = "0" ] &&
   [ "${INSTALL_LIB}" = "0" ]; then
	ALL=1;
	LIB_DIR=./target/lib
fi

if [ "${CLEAN}" = "1" ]; then
        rm -rf target/*
fi

if [ "${ALL}" = "1" ]; then
    mkdir -p ${LIB_DIR};
elif [ "${TEST}" = "1" ]; then
    mkdir -p ${LIB_DIR};
    mkdir -p ${BIN_DIR};
elif [ "${COVERAGE}" = "1" ]; then
    rm -f ${BIN_DIR}/cov
    rm -f ${BIN_DIR}/*.gcda
    rm -f ${LIB_DIR}/*
    mkdir -p ${BIN_DIR};
    mkdir -p ${LIB_DIR};
fi

ARCH=$(uname -m 2>/dev/null || echo unknown)

case "$ARCH" in
    x86_64|amd64)
	if [ "${VALGRIND}" = "1" ]; then
	    ARCH_FLAGS="-march=haswell -maes"
	else
	    if grep -q " avx2 " /proc/cpuinfo; then
                if grep -q " vaes " /proc/cpuinfo; then
                    ARCH_FLAGS="-march=${MARCH} -mavx2 -mvaes"
	        else
                    ARCH_FLAGS="-march=${MARCH} -mavx2 -maes"
	        fi
	    else
                ARCH_FLAGS=""
	    fi
	fi
        ;;
    aarch64|arm64|armv8*)
        ARCH_FLAGS="-march=${MARCH} -mno-outline-atomics"
        ;;
    *)
        ARCH_FLAGS="-march=${MARCH}"
        ;;
esac


if [ "${TEST}" = "1" ]; then
    LIBS="";
    NEED_LD=0;
    for SRC in "$INCLUDE_DIR"/libfam/*.h; do
        BASE=$(basename "${SRC}" .h)
	LIBS="${LIBS} -l${BASE}"
        IMPL=$(echo "$BASE" | tr 'a-z' 'A-Z')_IMPL
	SO_FILE="${LIB_DIR}/lib${BASE}.so"
	if [ ! -e "${SO_FILE}" ] || [ "${SRC}" -nt "${SO_FILE}" ]; then
            COMMAND="${CC} \
                ${INCLUDE} \
                ${ARCH_FLAGS} \
                ${CFLAGS} \
                ${CSTRICT} \
                -DTEST \
                -shared \
                -fPIC \
                -D${IMPL} \
                -x c  \
                ${SRC} \
               -o ${SO_FILE}";
            echo ${COMMAND};
            ${COMMAND} || exit 1;
	    NEED_LD=1;
	fi
    done
    MAIN_OBJECT="${LIB_DIR}/main.o";
    if [ ! -e "${MAIN_OBJECT}" ] || [ "${TEST_DIR}/main.c" -nt "${MAIN_OBJECT}" ]; then
        COMMAND="${CC} \
	    ${INCLUDE} \
	    ${ARCH_FLAGS} \
	    ${CFLAGS} \
	    ${CSTRICT} \
	    -o ${MAIN_OBJECT} \
	    ${TEST_DIR}/main.c -c";
        echo ${COMMAND};
        ${COMMAND} || exit 1;
	NEED_LD=1;
    fi
    BINARY="${BIN_DIR}/runtests";
    if [ ! -e "${BINARY}" ] || [ "${NEED_LD}" = "1" ]; then
        LDSO_PATH=`ldd /bin/ls | grep 'ld-linux' | awk '{print $1}'`;
        COMMAND="ld \
	    -o ${BINARY} \
	    ${LIB_DIR}/main.o \
	    -L${LIB_DIR} \
	    ${LIBS} \
	    -dynamic-linker ${LDSO_PATH}";
        echo ${COMMAND};
        ${COMMAND} || exit 1;
    fi
    if [ "${VALGRIND}" = "1" ]; then
	    LD_LIBRARY_PATH=${LIB_DIR} \
		    valgrind \
		    --child-silent-after-fork=yes \
                    --tool=memcheck \
                    --track-origins=yes \
                    --error-exitcode=1 \
		    ${BIN_DIR}/runtests || exit 1;
    else
        LD_LIBRARY_PATH=${LIB_DIR} ${BIN_DIR}/runtests || exit 1;
    fi
elif [ "${COVERAGE}" = "1" ]; then
	COMMAND="gcc \
		${ARCH_FLAGS} \
		-O0 \
		-g \
		-fno-builtin \
		${INCLUDE} \
		-DTEST \
		-DCOVERAGE \
		${TEST_DIR}/main.c \
		-o ${BIN_DIR}/cov \
		--coverage";
	echo ${COMMAND};
	${COMMAND} || exit 1;
	${BIN_DIR}/cov || exit 1;
	gcovr target/bin/cov-main.gcno
	gcovr target/bin/cov-main.gcno --txt-metric branch
elif [ "${ALL}" = "1" ]; then
    NEED_LIBFAM=0;
    IMPLS="";
    NL='
    ';
    for SRC in "$INCLUDE_DIR"/libfam/*.h; do
	BASE=$(basename "${SRC}" .h)
        IMPL=$(echo "$BASE" | tr 'a-z' 'A-Z')_IMPL
	IMPLS="${IMPLS}${NL}#define ${IMPL}${NL}#include <libfam/${BASE}.h>";
	SO_FILE="${LIB_DIR}/lib${BASE}.so"
        if [ ! -e "${SO_FILE}" ] || [ "${SRC}" -nt "${SO_FILE}" ]; then
            COMMAND="${CC} \
	        ${INCLUDE} \
                ${ARCH_FLAGS} \
                ${CFLAGS} \
                ${CSTRICT} \
                -shared \
                -fPIC \
                -D${IMPL} \
                -x c  \
                ${SRC} \
                -o ${LIB_DIR}/lib${BASE}.so"
            echo ${COMMAND};
            ${COMMAND} || exit 1;
	    NEED_LIBFAM=1;
	fi
    done
    cat > /tmp/fam.h <<EOM
${IMPLS}
EOM
    if [ "${NEED_LIBFAM}" = "1" ]; then
        COMMAND="${CC} ${INCLUDE} \
                ${ARCH_FLAGS} \
                ${CFLAGS} \
                ${CSTRICT} \
                -shared \
                -fPIC -x c /tmp/fam.h -o ${LIB_DIR}/libfam.so"
        echo ${COMMAND};
        ${COMMAND} || exit 1;
    fi
elif [ "${INSTALL}" = "1" ]; then
	rm -rf /usr/include/libfam
	cp -rp $INCLUDE_DIR/libfam /usr/include || exit 1;
elif [ "${INSTALL_LIB}" = "1" ]; then
	if [ ! -e ${LIB_DIR}/libfam.so ]; then
		echo "libfam.so does not exist! please run ./build all first.";
		exit 1;
	fi
	cp -rp ${LIB_DIR}/libfam.so /usr/lib || exit 1;
fi


